server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: composite
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      server:
        composite:
          - type: git
            uri: https://github.com/AlexandruAlexa1/config-repo.git
            username: ${GIT_USERNAME}
            password: ${GIT_PASSWORD}
            cloneOnStart: true
            default-label: main
            order: 1
          - type: vault
            host: ${VAULT_HOST:localhost}
            port: ${VAULT_HOST:8200}
            scheme: http
            backend: secret
            kv-version: 2
            order: 2

management:
  endpoints:
    web:
      exposure:
        include:
          - health
